name: pr title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: pr-title-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
